export const detailData = () => {
  var data = {
    code: "0000",
    msg: "success",
    data: {
      txId: 100001,
      txName: "我的体系1",
      children: [
        {
          txNodeId: 1000010001,   
          title: "一级节点",
          spread: true,
          level: 1,
          count: 100,
          hasLowerTxNode: true,
          children: [
            {
              txNodeId: 1100010002,
              title: "二级节点",
              spread: true,
              level: 1,
              count: 100,
              hasLowerTxNode: true,
              children: [
                {
                  txNodeId: 1110010003,
                  title: "3级节点",
                  spread: true,
                  level: 1,
                  count: 100,
                  hasLowerTxNode: true,
                  children: [
                    {
                      txNodeId: 1111010004,
                      title: "4级节点",
                      spread: true,
                      level: 1,
                      count: 100,
                      hasLowerTxNode: true,
                      children: [
                        {
                          txNodeId: 1100010005,
                          title: "二级节点",
                          spread: true,
                          level: 1,
                          count: 100,
                          hasLowerTxNode: false,
                          children: [],
                        },
                        {
                          txNodeId: 1111110006,
                          title: "5级节点",
                          spread: false,
                          level: 1,
                          count: 100,
                          hasLowerTxNode: false,
                          children: [],
                        },
                        {
                          txNodeId: 1111110007,
                          title: "5级节点",
                          spread: false,
                          level: 1,
                          count: 100,
                          hasLowerTxNode: false,
                          children: [],
                        },
                        {
                          txNodeId: 1111110008,
                          title: "5级节点",
                          spread: false,
                          level: 1,
                          count: 100,
                          hasLowerTxNode: false,
                          children: [],
                        },
                      ],
                    },
                    {
                      txNodeId: 1111010004,
                      title: "4级节点",
                      spread: true,
                      level: 1,
                      count: 100,
                      hasLowerTxNode: true,
                      children: [],
                    },
                  ],
                },
                {
                  txNodeId: 1110010003,
                  title: "3级节点",
                  spread: true,
                  level: 1,
                  count: 100,
                  hasLowerTxNode: true,
                  children: [],
                },
              ],
            },
            {
              txNodeId: 1100010003,
              title: "二级节点",
              spread: true,
              level: 1,
              count: 100,
              hasLowerTxNode: true,
              children: [],
            },
            {
              txNodeId: 1100010003,
              title: "二级节点",
              spread: true,
              level: 1,
              count: 100,
              hasLowerTxNode: true,
              children: [],
            },
          ],
        },
      ],
    },
  };
  return data;
};
